name: Build and Publish Maven Project

on:
  push:
    branches:
      - teste

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Maven
      run: mvn -B clean install

    - name: Publish to Maven repository
      uses: actions/publish-to-maven-central@v1
      with:
        server-id: my-maven-repository-id
        artifacts: 'target/*.jar'
        install-deps: true
